### ISSUE TITLE
Setting delay offset to more than 1 makes the host unresponding

### ISSUE THREAD

**Issue by louisroyer** [shynuu/trunks#6]
# Important notice if you try to reproduce this bug
1. Make sure you have no unsaved open document since the following will make your computer crash.
2. If you try to reproduce it using Docker, make sure to `systemctl disable docker.{service,socket}` to avoid restarting containers after boot (else you would need an [USB rescue key](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.1.0-amd64-netinst.iso) to disable docker manually with `rm /etc/systemd/system/{multi-user.target.wants/docker.service,sockets.target.wants/docker.socket}`).

# How to reproduce the bug
**Set delay offset to strictly more than 1**

Example:
```txt
ip link add d0 type dummy
ip link add d1 type dummy
ip addr add 10.0.200.130/24 dev d0
ip addr add 10.0.100.130/24 dev d1
ip link set up d0
ip link set up d1
# make sure you have read the important notice above !!
trunks --config trunks.yaml --flush 
```

```yaml
# trunks.yaml
# set the network device for satellite terminal and gateway.
nic:
  st: 10.0.200.130
  gw: 10.0.100.130

# configure the forward and return links available bandwidth in Mbits/s
bandwidth:
  forward: 20 
  return: 80

# configure the delay according to the GEO, MEO or LEO satellite and the offset, real delay = delay + or - offset
delay:
  value: 30
  offset: 2

# set the ACM simulation values
acm:
  - weight: 1
    duration: 10
  - weight: 0.8
    duration: 10
  - weight: 0.9
    duration: 10
  - weight: 0.5
    duration: 10
  - weight: 0.7
    duration: 10
```

Result when trunks is started directly on host (truncated):
```txt
Error: Qdisc not classful.
We have an error talking to the kernel
2023/08/29 15:25:35 Error running tc: exit status 2
```
And the whole interface freezes.
The error seems to be caused by [line 103 of runtime/trunks.go](https://github.com/shynuu/trunks/blob/9d472a254d63cbb5fa6df6a71088c0334028fa5e/runtime/trunks.go#L103C8-L103C8) (you can run `htop` before starting `trunks` to see the corresponding command using 100% of a CPU).

Result (truncated) when trunks is started on docker (for example `louisroyer/trunks`):
```txt
Message from syslogd@CometTail at Aug 23 15:37:12
 kernel: [687556.290166] watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [kworker/2:2:714224]
Message from syslogd@CometTail at Aug 23 15:37:36
 kernel: [687580.293920] watchdog: BUG: soft lockup - CPU#1 stuck for 45s! [tc:823338]
Message from syslogd@CometTail at Aug 23 15:37:12
 kernel: [687504.299213] watchdog: BUG: soft lockup - CPU#2 stuck for 48s! [kworker/2:2:714224]
```
I haven't saved docker logs from this container, but it will likely be the same as on host.

# Environment
```
$ uname -a
Linux CometTail 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
$ apt show trunks
Package: trunks
Version: 2.0.1+dfsg-2
# this is the current version from master along with a patch adding bash completions: https://github.com/louisroyer-deb/trunks/blob/debian/bookworm/debian/patches/0001-bash-completions.patch
$ apt show iproute2
Package: iproute2
Version: 6.1.0-3
$ apt show iptables
Package: iptables
Version: 1.8.9-2
$ apt show procps
Package: procps
Version: 2:4.0.2-3
$ apt show libc6
Package: libc6
Version: 2.36-9+deb12u1
$ tc -Version
tc utility, iproute2-6.1.0, libbpf 1.1.0
```

# Workaround
Don't set delay offset with the current version on Debian Bookworm.

# Bug origin
I think this is the result of an API change in `tc` and/or Linux. You can find the list of versions I tested to reproduce the crash on [this gist](https://gist.github.com/louisroyer/90636c07dc4b205b813a56de718d9d09)

# Proposed solution
Since the bug seems fixed for newer versions of Linux/tc, I suggest to add a "known issues" section in the README.
If we are able to determine with more precision which versions are impacted, we could parse `tc -Version`/`uname --kernel-version` output to shutdown trunks gracefully with an error when a delay offset is set. It seems a better option than just crashing the whole system.
